# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_example',
                'doc_host': 'https://davidweinberg.github.io',
                'git_url': 'https://github.com/davidweinberg/nbdev_example',
                'lib_path': 'nbdev_example'},
  'syms': {'nbdev_example.core': {'nbdev_example.core.foo': ('core.html#foo', 'nbdev_example/core.py')}}}
